name = "glyph"
version = "0.2.0"

description = "A purely Gleam Discord library built from the ground up with stratus."
licences = ["Apache-2.0"]
repository = { type = "github", user = "grottohub", repo = "glyph" }
links = [{ title = "Website", href = "https://gleam.run" }]

target = "erlang"
gleam = ">= 1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
stratus = "~> 0.5"
gleam_hackney = "~> 1.2"
gleam_json = "~> 1.0"
gleam_http = "~> 3.6"
gleam_otp = "~> 0.10"
gleam_erlang = "~> 0.24"
logging = "~> 1.0"
prng = "~> 3.0"
carpenter = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 1.0"
